вычисление факториала
js-tasks-ru/jsbasic-20231109_eduard019 pull request #2
Opened 2023-11-14 16:51 UTC by elvis110

2023-11-14 16:52 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-14 18:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-15 12:39 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-15 12:40 UTC, SinimaWath requested changes

2023-11-15 12:40 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  if(name.indexOf(' ') === -1 && name.length >= 4){
попробуй вызвать функцию isValid, со значением null: `isValid(null)`, также в случае если имя не валидной, должно возвращаться `false`, в твоем случае ничего не возвращается

2023-11-15 12:40 UTC, SinimaWath commented on 1-module/1-task/index.js
> +}
Тут нет необходимости в else:
```
if (n ==0 || n == 1) {
  return 1
}

for (let i = 2; i <= n; i++) {
   f = f * i;
}

return f

```

2023-11-15 18:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-16 11:59 UTC, SinimaWath approved these changes

2023-11-16 12:00 UTC, merged